<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dasm</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>6502 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>([#$%][a-fA-F0-9#$%]+)</string>
			<key>name</key>
			<string>constant.numeric.6502asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b[0-9]+\b)</string>
			<key>name</key>
			<string>constant.numeric.6502asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(lda|ldx|ldy|sta|stx|sty|tax|tay|txa|tya|tsx|txs|pha|php|pla|plp|and|eor|ora|bit|adc|sbc|cmp|cpx|cpy|inc|inx|iny|dec|dex|dey|asl|lsr|rol|ror|jmp|jsr|rts|bcc|bcs|beq|bmi|bne|bpl|bvc|bvs|clc|cdl|cli|clv|sec|sed|sei|brk|nop|rti)\b</string>
			<key>name</key>
			<string>keyword.6502asm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.label.6502asm</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>start of line string is a label</string>
			<key>match</key>
			<string>^([.a-zA-Z0-9]+)</string>
			<key>name</key>
			<string>constant.other.label.6502asm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.semicolon.heading.6502asm</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>segments captured for inclusion in symbol list</string>
			<key>match</key>
			<string>^; (Constants|RAM|Start of ROM|Vertical Blank|Kernel|Overscan|ROM Tables)</string>
			<key>name</key>
			<string>comment.line.semicolon.heading.6502asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(processor|include|align|boundary|org|seg|u|end|echo|Bank[0-9]|word|byte|ds|dc|dv|[bwl]|hex|rorg|subroutine|mac|endm)\b</string>
			<key>name</key>
			<string>keyword.control.import.6502asm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.6502asm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.6502asm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s+\b(processor|include|seg|org|echo|align|boundary|if|eif|ifconst|ifnconst|mac)\b([^;]+)</string>
			<key>name</key>
			<string>meta.preprocessor.macro.c</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(echo|equ|eqm|set|mexit|ifconst|ifnconst|if|else|endif|eif|repeat|repend)\b</string>
			<key>name</key>
			<string>support.function.6502asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(sleep|set_pointer|vertical_sync|clean_start|boundary)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(wsync|vblank|vsync|sds|rsync|nusiz0|nusiz1|colup0|colup1|colupf|colubk|ctrlpf|refp0|refp1|pf0|pf1|pf2|resp0|resp1|resm0|resm1|resbl|audc0|audc1|audf0|audf1|audv0|audv1|grp0|grp1|enam0|enam1|enabl|hmp0|hmp1|hmm0|hmm1|hmbl|vdelp0|vdelp1|vdelbl|resmp0|resmp1|hmove|hmclr|cxclr|cxm0p|cxm1p|cxp0fb|cxp1fb|cxm0fb|cxm1fb|cxblpf|cxppmm|inpt0|inpt1|inpt2|inpt3|inpt4|inpt5|swcha|swacnt|swchb|swbcnt|intim|timint|tim1t|tim8t|tim64t|t1024t)\b</string>
			<key>name</key>
			<string>support.constant.6502asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line.semicolon.6502asm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.6502asm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>custom_label</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#custom_label</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.6502asm</string>
	<key>uuid</key>
	<string>7584AFCC-BCBB-4781-83BF-CBD38A21A152</string>
</dict>
</plist>
